"""Generate Excel field mapping for device, intf, ponport DB tables.
Columns sourced from pmsonline DB (host=10.50.238.194) in ordinal order.
"""

from pathlib import Path
import psycopg2
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# ---------------------------------------------------------------------------
# Field mapping definitions
# (db_column, status, discovery_item, api_field, value_example, remark)
# status: "Populated" | "NotImplement" | "NotSupported"
# ---------------------------------------------------------------------------

MAPPING = {
  # ---- device ----
  "device": {
    "id":               ("NotImplement", "—",                   "DB auto-generated PK",                                            "",                          "Generated by DB on insert; not from Nokia NBI"),
    "a_homing_id":      ("NotSupported", "—",                   "—",                                                               "",                          "Aggregation homing ID — static topology config, not in Altiplano NBI"),
    "a_homing_site":    ("NotSupported", "—",                   "—",                                                               "",                          "Aggregation homing site — static topology config, not in Altiplano NBI"),
    "agent":            ("Populated",    "Hardcoded",           "—",                                                               "altiplano",                 "Fixed value identifying collection agent"),
    "b_homing_id":      ("NotSupported", "—",                   "—",                                                               "",                          "Backup homing ID — static topology config, not in Altiplano NBI"),
    "b_homing_site":    ("NotSupported", "—",                   "—",                                                               "",                          "Backup homing site — static topology config, not in Altiplano NBI"),
    "c_homing_id":      ("NotSupported", "—",                   "—",                                                               "",                          "Static topology config, not in Altiplano NBI"),
    "c_homing_site":    ("NotSupported", "—",                   "—",                                                               "",                          "Static topology config, not in Altiplano NBI"),
    "chassisid":        ("NotImplement", "SLOT-INV (6)",        "eqpt:slot-inventory → Chassis.serial-num",                        "",                          "eqpt module not available on firmware 25.6"),
    "community":        ("NotSupported", "—",                   "—",                                                               "",                          "SNMP community string — external credential store, not in Altiplano NBI"),
    "descr":            ("Populated",    "SLOT-INV (6)",        "hardware-type (fallback: ES-DEVICE configuration.hardware-type)", "LS-MF-LANT-A",             "Hardware type string from Nokia intent"),
    "first":            ("Populated",    "Discovery timestamp", "—",                                                               "2025-06-08T10:00:00",       "UTC timestamp of discovery run"),
    "hop":              ("NotSupported", "—",                   "—",                                                               "",                          "Network hop count — not in Altiplano NBI"),
    "ip":               ("Populated",    "ES-DEVICE (3)",       "configuration.ip-address[0]",                                     "10.237.77.221",             ""),
    "last_modify_at":   ("Populated",    "Discovery timestamp", "—",                                                               "2025-06-08T10:00:00",       "UTC timestamp of discovery run"),
    "last_modify_by":   ("Populated",    "Hardcoded",           "—",                                                               "nokia-discovery",           ""),
    "lastseen":         ("Populated",    "Discovery timestamp", "—",                                                               "2025-06-08T10:00:00",       "Not a live heartbeat — set at discovery run time"),
    "model":            ("NotImplement", "SLOT-INV (6)",        "eqpt:slot-inventory → Chassis.model",                             "",                          "eqpt module not available on firmware 25.6"),
    "name":             ("Populated",    "ES-DEVICE (3)",       "target.device-name",                                              "QCENGNKMF2",               ""),
    "network":          ("NotSupported", "—",                   "—",                                                               "",                          "Static topology config — not in Altiplano NBI"),
    "pn":               ("NotImplement", "SLOT-INV (6)",        "eqpt:slot-inventory → Chassis.code",                              "",                          "eqpt module not available on firmware 25.6"),
    "required-network-state": ("Populated", "ES-DEVICE (3)",     "required-network-state (raw value)",                              "active",                    "Intent state, not live device poll status"),
    "usr_pollstatus":   ("Populated",    "Hardcoded",           "—",                                                               "1",                         ""),
    "pollint":          ("Populated",    "Hardcoded",           "—",                                                               "86400",                     "Seconds (24 hours)"),
    "province":         ("NotSupported", "—",                   "—",                                                               "",                          "Static site mapping — not in Altiplano NBI"),
    "region":           ("NotSupported", "—",                   "—",                                                               "",                          "Static site mapping — not in Altiplano NBI"),
    "ringid":           ("NotSupported", "—",                   "—",                                                               "",                          "Ring ID — static topology config"),
    "ringtopo":         ("NotSupported", "—",                   "—",                                                               "",                          "Ring topology type — static topology config"),
    "rn":               ("NotSupported", "—",                   "—",                                                               "",                          "Ring node ID — static topology config"),
    "sitename":         ("NotSupported", "—",                   "—",                                                               "",                          "Static site mapping — not in Altiplano NBI"),
    "topology":         ("NotSupported", "—",                   "—",                                                               "",                          "Static topology config — not in Altiplano NBI"),
    "vendor":           ("Populated",    "Hardcoded",           "—",                                                               "Nokia",                     "Fixed value"),
    "disc_id":          ("NotImplement", "—",                   "DB foreign key to discovery run",                                 "",                          "Generated by DB; not from Nokia NBI"),
    "uplink_ip1":       ("NotSupported", "—",                   "—",                                                               "",                          "Upstream device IP — requires LLDP or manual mapping"),
    "uplink_ip2":       ("NotSupported", "—",                   "—",                                                               "",                          "Secondary uplink IP — requires LLDP or manual mapping"),
    "uplink_model1":    ("NotSupported", "—",                   "—",                                                               "",                          "Upstream device model — requires LLDP or manual mapping"),
    "uplink_model2":    ("NotSupported", "—",                   "—",                                                               "",                          "Secondary uplink model — requires LLDP or manual mapping"),
    "uplink_site1":     ("NotSupported", "—",                   "—",                                                               "",                          "Upstream site — requires manual mapping"),
    "uplink_site2":     ("NotSupported", "—",                   "—",                                                               "",                          "Secondary uplink site — requires manual mapping"),
    "dn":               ("NotSupported", "—",                   "—",                                                               "",                          "Domain name — not in Altiplano NBI"),
    "swversion":        ("Populated",    "SLOT-INV (6)",        "swversion (fallback: ES-DEVICE configuration.device-version)",    "25.6",                      ""),
    "latitude":         ("NotSupported", "—",                   "—",                                                               "",                          "Site coordinates — not in Altiplano NBI"),
    "longitude":        ("NotSupported", "—",                   "—",                                                               "",                          "Site coordinates — not in Altiplano NBI"),
    "olttype":          ("NotImplement", "mapping.py",          "Set to None in mapping.py; not derived during discovery",         "",                          "olttype mapping removed from discovery — assigned downstream at mapping stage"),
    "sysuptime":        ("NotSupported", "—",                   "—",                                                               "",                          "SNMP OID 1.3.6.1.2.1.1.3.0 only — no equivalent in Altiplano NBI"),
  },

  # ---- intf ----
  "intf": {
    "id":               ("NotImplement", "RC-INTF (9)",         "Composite: {device.id}.{ifindex}",                                "",                          "RC-Proxy not deployed on testbed"),
    "device_id":        ("NotImplement", "RC-INTF (9)",         "FK from device table",                                            "",                          "RC-Proxy not deployed on testbed"),
    "device_ip":        ("Populated",    "ES-DEVICE (3)",       "configuration.ip-address[0]",                                     "10.237.77.221",             ""),
    "dstport":          ("NotSupported", "—",                   "—",                                                               "",                          "Neighbor port — requires LLDP or manual mapping"),
    "dstsite":          ("NotSupported", "—",                   "—",                                                               "",                          "Neighbor site — requires manual mapping"),
    "dsttype":          ("NotSupported", "—",                   "—",                                                               "",                          "Neighbor device type — requires manual mapping"),
    "first":            ("Populated",    "Discovery timestamp", "—",                                                               "2025-06-08T10:00:00",       ""),
    "ifadmin":          ("Populated",    "UPLINK-SFP (7)",      "sfp-status:output.inventory[].admin-status",                      "up",                        "disable→down, else up. NotImplement if SFP slot empty (e.g. QCENGNKMF2)"),
    "ifalias":          ("NotImplement", "RC-INTF (9)",         "ietf-interfaces:interfaces-state.interface[].description",        "",                          "RC-Proxy not deployed on testbed"),
    "ifdescr":          ("Populated",    "UPLINK-SFP (7)",      "Same as ifname (port_id)",                                        "nt-a:xfp:1",               "Nokia NBI has no separate description for uplink port"),
    "ifindex":          ("NotImplement", "RC-INTF (9)",         "ietf-interfaces:interfaces-state.interface[].if-index",           "",                          "RC-Proxy not deployed on testbed"),
    "ifname":           ("Populated",    "UPLINK-SFP (7)",      "uplink-connection ES intent → configuration.port-id[0]",         "nt-a:xfp:1",               "One row per uplink port per OLT"),
    "ifoper":           ("Populated",    "UPLINK-SFP (7)",      "sfp-status:output.inventory[].oper-status",                       "up",                        "NotImplement if SFP slot empty (e.g. QCENGNKMF2)"),
    "ifphyaddr":        ("NotImplement", "RC-INTF (9)",         "ietf-interfaces:interfaces-state.interface[].phys-address",       "",                          "RC-Proxy not deployed on testbed"),
    "ifspeed":          ("NotImplement", "RC-INTF (9)",         "ietf-interfaces:interfaces-state.interface[].speed",              "",                          "RC-Proxy not deployed on testbed"),
    "iftype":           ("Populated",    "Hardcoded",           "—",                                                               "ethernetCsmacd",            "Fixed for all uplink ethernet ports"),
    "last_modify_at":   ("Populated",    "Discovery timestamp", "—",                                                               "2025-06-08T10:00:00",       ""),
    "last_modify_by":   ("Populated",    "Hardcoded",           "—",                                                               "nokia-discovery",           ""),
    "lastseen":         ("Populated",    "Discovery timestamp", "—",                                                               "2025-06-08T10:00:00",       ""),
    "mediatype":        ("Populated",    "UPLINK-SFP (7)",      "Derived from sfp-status wave-length",                             "SM",                        "1310/1490/1550nm→SM, 850nm→MM. None if SFP slot empty"),
    "sys_pollstatus":   ("Populated",    "Hardcoded",           "—",                                                               "1",                         ""),
    "usr_pollstatus":   ("Populated",    "Hardcoded",           "—",                                                               "1",                         ""),
    "dstname":          ("NotSupported", "—",                   "—",                                                               "",                          "Neighbor device name — requires LLDP or manual mapping"),
    "device_name":      ("Populated",    "ES-DEVICE (3)",       "target.device-name",                                              "QCENGNKMF2",               ""),
    "name":             ("Populated",    "UPLINK-SFP (7)",      "Composite: {device_name}:{port_id}",                              "SMK01058GO0:nt-a:xfp:1",   ""),
    "ifconn":           ("NotImplement", "RC-INTF (9)",         "Derived from ifoper",                                             "",                          "RC-Proxy not deployed on testbed"),
    "remdstsite":       ("NotSupported", "—",                   "—",                                                               "",                          "Remote destination site — requires manual mapping"),
    "dstsite2":         ("NotSupported", "—",                   "—",                                                               "",                          "Secondary neighbor site — requires manual mapping"),
    "dsttype2":         ("NotSupported", "—",                   "—",                                                               "",                          "Secondary neighbor device type — requires manual mapping"),
    "moduleclass":      ("Populated",    "UPLINK-SFP (7)",      "Derived from port_id type token",                                 "10GE-XFP",                  "xfp→10GE-XFP, qsfp→100GE-QSFP28, sfp→1GE-SFP"),
    "vendorpn":         ("Populated",    "UPLINK-SFP (7)",      "sfp-status:output.inventory[].part-number (first token)",        "3FE62600AA",               "None if SFP slot empty"),
    "altname":          ("NotSupported", "—",                   "—",                                                               "",                          "Optional alternate name — not in Altiplano NBI"),
  },

  # ---- ponport ----
  "ponport": {
    "id":               ("NotImplement", "RC-INTF-ONE (10)",    "Composite: {device.id}.{ifindex}",                                "",                          "RC-Proxy not deployed on testbed"),
    "device_id":        ("NotImplement", "RC-INTF-ONE (10)",    "FK from device table",                                            "",                          "RC-Proxy not deployed on testbed"),
    "device_ip":        ("Populated",    "ES-DEVICE (3)",       "configuration.ip-address[0]",                                     "10.237.77.221",             ""),
    "device_name":      ("Populated",    "ES-DEVICE (3)",       "target.device-name",                                              "QCENGNKMF2",               ""),
    "dl_bw_remaining":  ("NotImplement", "OpenTSDB",            "PON utilization counter",                                         "",                          "Requires §4.2.15 (Enable PON Utilization Monitoring) enabled on device first"),
    "first":            ("Populated",    "Discovery timestamp", "—",                                                               "2025-06-08T10:00:00",       ""),
    "ifadmin":          ("Populated",    "PON-SFP (8)",         "fiber:fiber → pon-port[].admin-state",                            "up",                        "unlocked→up, locked→down, absent→up (YANG default). Intent config state, not live RC-Proxy state"),
    "ifalias":          ("NotSupported", "—",                   "—",                                                               "",                          "Not applicable for PON ports"),
    "ifconn":           ("Populated",    "ES-ONT (5)",          "Count of ONTs on this fiber (ES agg size=0 per fiber)",           "1810",                      "Total provisioned ONT count per PON port"),
    "ifdescr":          ("Populated",    "ES-FIBER (4)",        "target.fiber-name (same as ifname)",                              "QCENGNKMF2-1-16",          "Nokia NBI has no separate description for fiber"),
    "ifindex":          ("NotImplement", "RC-INTF-ONE (10)",    "ietf-interfaces:interface.if-index",                              "",                          "RC-Proxy not deployed on testbed"),
    "ifname":           ("Populated",    "ES-FIBER (4)",        "target.fiber-name",                                               "QCENGNKMF2-1-16",          ""),
    "ifoper":           ("Populated",    "ES-FIBER (4)",        "required-network-state: active→up, others→down",                  "up",                        "Intent state, NOT live device oper-status. Live oper-status requires RC-Proxy (item 10 — blocked)"),
    "ifphyaddr":        ("NotSupported", "—",                   "—",                                                               "",                          "PON ports have no MAC address"),
    "ifspeed":          ("Populated",    "ES-FIBER (4)",        "xpon-type mapped to bps",                                         "10000000000",               "gpon=2488000000, xgs-pon/mpm-gpon-xgs=10000000000"),
    "iftype":           ("Populated",    "ES-FIBER (4)",        "configuration.xpon-type[0] mapped via XPON_TYPE_MAP",             "xgs-pon",                   "gpon/xgs-pon/mpm-gpon-xgs → gpon/xgs-pon"),
    "l1_dl_max_bw":     ("Populated",    "ES-FIBER (4)",        "xpon-type mapped to Mbps DL",                                     "10240",                     "gpon=2488, xgs-pon/mpm-gpon-xgs=10240"),
    "l1_ul_max_bw":     ("Populated",    "ES-FIBER (4)",        "xpon-type mapped to Mbps UL",                                     "10240",                     "gpon=1244, xgs-pon/mpm-gpon-xgs=10240"),
    "l1sp":             ("Populated",    "ES-FIBER (4)",        "configuration.port-profile[0]",                                   "Default_Port_Mix_authentication","Line speed/service profile name"),
    "last_modify_at":   ("Populated",    "Discovery timestamp", "—",                                                               "2025-06-08T10:00:00",       ""),
    "last_modify_by":   ("Populated",    "Hardcoded",           "—",                                                               "nokia-discovery",           ""),
    "lastseen":         ("Populated",    "Discovery timestamp", "—",                                                               "2025-06-08T10:00:00",       ""),
    "name":             ("Populated",    "ES-FIBER (4)",        "Composite: {device_name}:{ponport}",                              "QCENGNKMF2:1-1-1-16",      ""),
    "ponport":          ("Populated",    "ES-FIBER (4)",        "configuration.pon-id[0] parsed: LT1.PON16 → 1-1-1-16",           "1-1-1-16",                 "Fallback: parse fiber name if pon-id absent"),
    "sys_pollstatus":   ("Populated",    "Hardcoded",           "—",                                                               "1",                         ""),
    "ul_bw_remaining":  ("NotImplement", "OpenTSDB",            "PON utilization counter",                                         "",                          "Requires §4.2.15 (Enable PON Utilization Monitoring) enabled on device first"),
    "usr_pollstatus":   ("Populated",    "Hardcoded",           "—",                                                               "1",                         ""),
    "moduleclass":      ("Populated",    "PON-SFP (8)",         "fiber:fiber → pon-port[].xpon-type mapped via XPON_TO_MODULECLASS","GPON/XGS-PON (combo)",    "gpon→GPON CLASS B+, xgs-pon→XGS-PON, mpm-gpon-xgs→GPON/XGS-PON (combo)"),
    "vendorpn":         ("Populated",    "PON-SFP (8)",         "fiber:fiber → pon-port[].model-name, part number parsed from (...) at end","3FE47581BD",       "Regex extracts part number from end of model-name string"),
  },
}

# ---------------------------------------------------------------------------
# Styling
# ---------------------------------------------------------------------------

HEADER_FILL = PatternFill("solid", fgColor="1F4E79")
HEADER_FONT = Font(bold=True, color="FFFFFF", size=10)

STATUS_FILLS = {
  "Populated":    PatternFill("solid", fgColor="E2EFDA"),
  "NotImplement": PatternFill("solid", fgColor="FFF2CC"),
  "NotSupported": PatternFill("solid", fgColor="FCE4D6"),
}
STATUS_FONTS = {
  "Populated":    Font(color="375623", size=10),
  "NotImplement": Font(color="7F6000", size=10),
  "NotSupported": Font(color="843C0C", size=10),
}

ROW_FILL_ODD  = PatternFill("solid", fgColor="F2F2F2")
ROW_FILL_EVEN = PatternFill("solid", fgColor="FFFFFF")

THIN = Side(style="thin", color="BFBFBF")
THIN_BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)

COL_HEADERS = ["DB Column", "Data Type", "Nullable", "Status", "Discovery Item", "API Field / Source", "Example Value", "Remark"]
COL_WIDTHS  = [22, 14, 9, 16, 20, 52, 34, 56]


def _write_sheet(ws, table: str, db_cols: list, mapping: dict) -> None:
  # Header
  for ci, h in enumerate(COL_HEADERS, 1):
    c = ws.cell(row=1, column=ci, value=h)
    c.font = HEADER_FONT
    c.fill = HEADER_FILL
    c.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    c.border = THIN_BORDER
  ws.row_dimensions[1].height = 22

  for ri, (col_name, data_type, char_len, nullable, _) in enumerate(db_cols, 2):
    type_str = f"varchar({char_len})" if char_len else data_type
    nullable_str = "YES" if nullable == "YES" else "NO"
    m = mapping.get(col_name, ("NotSupported", "—", "—", "", "Not mapped"))
    status, item, api_field, example, remark = m
    is_odd = ri % 2 == 1

    row_vals = [col_name, type_str, nullable_str, status, item, api_field, example, remark]
    for ci, val in enumerate(row_vals, 1):
      c = ws.cell(row=ri, column=ci, value=val)
      c.border = THIN_BORDER
      c.alignment = Alignment(vertical="top", wrap_text=True)

      if ci == 4:  # Status column
        c.fill = STATUS_FILLS.get(status, ROW_FILL_ODD)
        c.font = STATUS_FONTS.get(status, Font(size=10))
        c.alignment = Alignment(horizontal="center", vertical="top")
      elif ci == 1:  # Column name
        c.fill = ROW_FILL_ODD if is_odd else ROW_FILL_EVEN
        c.font = Font(bold=True, size=10, color="1F4E79")
      else:
        c.fill = ROW_FILL_ODD if is_odd else ROW_FILL_EVEN
        c.font = Font(size=10)

  for ci, w in enumerate(COL_WIDTHS, 1):
    ws.column_dimensions[get_column_letter(ci)].width = w

  ws.freeze_panes = "A2"
  ws.auto_filter.ref = f"A1:{get_column_letter(len(COL_HEADERS))}1"

  # Summary
  ws.append([])
  total     = len(db_cols)
  populated = sum(1 for c in db_cols if mapping.get(c[0], ("NotSupported",))[0] == "Populated")
  not_impl  = sum(1 for c in db_cols if mapping.get(c[0], ("NotSupported",))[0] == "NotImplement")
  not_sup   = sum(1 for c in db_cols if mapping.get(c[0], ("NotSupported",))[0] == "NotSupported")
  sr = ws.max_row + 1
  ws.cell(row=sr, column=1, value="Summary").font = Font(bold=True, size=10)
  ws.cell(row=sr, column=2, value=f"Total: {total}   Populated: {populated}   NotImplement: {not_impl}   NotSupported: {not_sup}").font = Font(italic=True, size=9, color="595959")
  ws.merge_cells(f"B{sr}:{get_column_letter(len(COL_HEADERS))}{sr}")


def main():
  conn = psycopg2.connect(
    host="10.50.238.194", port=5432, dbname="pmsonline",
    user="pmsonline", password="pmsonline", sslmode="disable",
  )
  cur = conn.cursor()

  wb = openpyxl.Workbook()
  wb.remove(wb.active)

  for table in ["device", "intf", "ponport"]:
    cur.execute("""
      SELECT column_name, data_type, character_maximum_length, is_nullable, column_default
      FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = %s
      ORDER BY ordinal_position
    """, (table,))
    db_cols = cur.fetchall()
    ws = wb.create_sheet(title=table)
    _write_sheet(ws, table, db_cols, MAPPING[table])
    print(f"  {table}: {len(db_cols)} columns")

  conn.close()

  out = Path("output/nokia_nbi_field_mapping.xlsx")
  wb.save(out)
  print(f"Saved: {out}")


if __name__ == "__main__":
  main()
